"""Assemble a ready-to-push Hugging Face Space directory.

Why a script: the Space needs a *different* shape from the GitHub repo — it carries the corpus
(which is gitignored on GitHub), it needs HF's README frontmatter, and it needs LFS tracking for
the big binaries. Doing that by hand is error-prone, and getting it wrong means a failed build
after an 800 MB push.

What ships (and what deliberately does not) mirrors .dockerignore: page images + SQLite + the
chunked index go; the late-interaction visual index does not (measured out of the champion —
see docs/RESULTS.md), nor does the local LLM response cache or .env.

Usage:
    python scripts/prepare_space.py --out ../sightline-space --title "Sightline"
Then:
    cd ../sightline-space && git init && git lfs install
    git remote add origin https://huggingface.co/spaces/<you>/sightline
    git add -A && git commit -m "Sightline v1.0" && git push -u origin main
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Code + config the image needs. Mirrors the Dockerfile's COPY lines.
INCLUDE = ["src", "scripts", "pyproject.toml", "Dockerfile", ".dockerignore"]

# Corpus pieces the champion actually serves from.
DATA_INCLUDE = [
    Path("data/pages"),
    Path("data/sightline.db"),
    Path("data/qdrant/collection/sightline_text_chunks"),
    Path("data/qdrant/meta.json"),
]

# HF Spaces reads this frontmatter to configure the Space. sdk=docker + app_port=7860.
SPACE_README = """---
title: {title}
emoji: 📄
colorFrom: green
colorTo: gray
sdk: docker
app_port: 7860
pinned: false
---

# {title}

Ask analyst-grade questions about SEC filings and get answers with **page-level citations** —
or an honest refusal when the corpus can't support an answer.

- **`/`** — overview
- **`/app`** — the console: ask a question, see the cited page images inline with the
  answer's figures boxed on the page, plus a stage-by-stage trace of how the answer was produced.

Retrieval is measured, not asserted: **Recall@5 0.752** on a 54-case hand-verified benchmark
across 15 companies / 32 filings / 2,353 page images, with every configuration (including the
ones that lost) recorded in the project's results log.

Answers are generated by a hosted model on a free tier, so a public demo is rate-limited;
repeated questions are served from a response cache.
"""

# LFS for the big binaries. Page PNGs are ~325 KB each — fine as regular git objects, and
# keeping them out of LFS avoids burning LFS quota on 2,353 small files.
GITATTRIBUTES = """*.db filter=lfs diff=lfs merge=lfs -text
*.bin filter=lfs diff=lfs merge=lfs -text
*.mdb filter=lfs diff=lfs merge=lfs -text
data/qdrant/** filter=lfs diff=lfs merge=lfs -text
"""


def copy_into(out: Path) -> None:
    for rel in INCLUDE:
        src = REPO / rel
        if not src.exists():
            raise SystemExit(f"missing {rel} — run from a complete checkout")
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, dst, dirs_exist_ok=True,
                            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
        else:
            shutil.copy2(src, dst)

    for rel in DATA_INCLUDE:
        src = REPO / rel
        if not src.exists():
            print(f"  ! skipping {rel} (not found)")
            continue
        dst = out / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.is_dir():
            shutil.copytree(src, dst, dirs_exist_ok=True)
        else:
            shutil.copy2(src, dst)


def dir_size_mb(p: Path) -> float:
    return sum(f.stat().st_size for f in p.rglob("*") if f.is_file()) / 1024 / 1024


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="target directory for the Space checkout")
    ap.add_argument("--title", default="Sightline")
    args = ap.parse_args()

    out = Path(args.out).resolve()
    if out.exists() and any(out.iterdir()):
        raise SystemExit(f"{out} exists and is not empty — remove it or pick another --out")
    out.mkdir(parents=True, exist_ok=True)

    print(f"assembling Space in {out}")
    copy_into(out)
    (out / "README.md").write_text(SPACE_README.format(title=args.title), encoding="utf-8")
    (out / ".gitattributes").write_text(GITATTRIBUTES, encoding="utf-8")

    print(f"\n  total: {dir_size_mb(out):.0f} MB")
    print(f"  pages: {dir_size_mb(out / 'data/pages'):.0f} MB")
    print("\nNext:")
    print(f"  cd {out}")
    print("  git init && git lfs install")
    print("  git remote add origin https://huggingface.co/spaces/<you>/sightline")
    print('  git add -A && git commit -m "Sightline v1.0" && git push -u origin main')
    print("\nThen set these as Space secrets (Settings -> Variables and secrets):")
    print("  LLM_API_KEY, LLM_BASE_URL, LLM_MODEL, ROUTER_MODEL,")
    print("  LLM_MIN_INTERVAL_S, SEC_USER_AGENT")


if __name__ == "__main__":
    main()
